### ISSUE TITLE
Explorer Context Menu Support in Message File List

### ISSUE THREAD

**Issue by flywire** [Dijji/XstReader#13]
Using Win10.

1. It would be nice to support Explorer context menu in message file list
2. Message context menu opens print preview in application window - would be better to open in new window
3. Message context menu does not give access to page settings (headers, margins etc) when selecting print (use print preview as workaround)
4. Message Save File supports multiple file selection - nice

**Comment by Dijji** [comment]
It sounds as though this is mostly about printing emails. I regard printing as a hard problem that is currently out of scope, unless you can suggest an easy way to do it.

Dijji

**Comment by flywire** [comment]
No, printing was really an aside to explorer context menu. I formed the view from your other repositories you have some expertise with this functionality (??).

Re Printing: Works well in message from context menu but does not seem to support page customisation - hence my suggestion of print preview in a new window if user is fussy since application window size may be unsuitable.

**Comment by Dijji** [comment]
Adding a context menu to the message list would be easy enough, but the question is, what should the entries on it be? Modifying printing I still regard as too hard - printing from the message window comes for free.

Would supporting opening attachments not make more sense from the attachment list?

Dijji

**Comment by flywire** [comment]
> Modifying printing I still regard as too hard

Fair enough, functional but not necessarily nice as I say above.

> Would supporting opening attachments not make more sense from the attachment list?

That is what I had in mind

**Comment by Dijji** [comment]
Makes sense. Opening attachments also matches an Outlook capability. I will add it to my development list, though at a slightly lower priority.

Dijji

**Comment by flywire** [comment]
Can I see the development list?

**Comment by Dijji** [comment]
On this project, it is currently just the two items arising from your two issues. Care to help?

Dijji

**Comment by flywire** [comment]
I'd like to but I know zero c#. Old procedural languages including vb and a bit of python. Been looking through the java tutorials.

**Comment by flywire** [comment]
https://github.com/Dijji/XstReader/issues/14#issuecomment-559045690
> * attachments are too difficult to view when browsing emails

https://github.com/Dijji/XstReader/issues/14#issuecomment-559097777
> I can see how to deliver on some of what you want.
> 
> * I can open an attachment using the associated default application, but I cannot see how to allow you to do the equivalent of Open With…

This is far better than 80/20 rule.  Double click to open?

**Comment by Dijji** [comment]
I have made some progress with attachment opening. After a bit more research, I now have both Open and Open With working in a test build, driven by a context menu on the attachments list, so this could be ready for release before too long.

**Comment by Dijji** [comment]
Support for attachment opening is now available in the pre-release of version 1.7. If you are interested, check it out and let me know what you think.

**Comment by flywire** [comment]
Very functional now.
