### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ElViajero2019** [Dijji/XstReader#16]
Nice tool, works great.  Is there a function to search for specific messages?

thanks,

**Comment by Dijji** [comment]
There isn't. However, it would be fairly simple to add one that searched through headline information (subject, to, from). Would this be of any use to you? A full text search of email content is rather beyond the intended scope of the tool.

Dijji

**Comment by ElViajero2019** [comment]
Hello and thanks.  Yes!  A search as you describe would be incredibly useful.  Thanks again.

**Comment by Dijji** [comment]
This has been addressed in the release of Version 1.6

Let me know what you think.

**Comment by flywire** [comment]
Search works -yeah!!!

I think would be better highlighting matching messages and/or filtered list

**Comment by Dijji** [comment]
Thank you for the feedback, it is always much appreciated.

I could claim artistic differences (I believe that you can get everything done either way, e.g., searching backwards through 2010 for a mail with bread in the subject), but actually, my clincher here was degree of difficulty. Filtering or highlighting means searching the entire body of messages before you are, in theory, ready to present an answer, and for large message folders, this just takes too long. Outlook deals with this by presenting partial results, then adding to them as a background worker comes up with more. Pretty complex. But if you only look for one message at a time, the implementation is much simpler and you only get the delays in the extreme cases of long stretches between hits, not on every search through a large folder.

Dijji
