### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by flywire** [Dijji/XstReader#17]
Can you provide brief build instructions somewhere? It would be preferable to include links to resources/software. Non-programmers can compile a program to access pre-release code features and even tweak a few things here and there.

**Comment by halueda** [comment]
I think porviding  a file named HowtoBuild.md just under top directory is nice.

The way is farely simple.
PreCondition:
  - The whole XstReader is placed in a PC by doing git pull or downloading source zip.

Procedure:
- Download and install VisualStudio Community from https://visualstudio.microsoft.com/
    - Note that C# development is included.
- Double click XstReader.csproj
- Compile and run in the VisualStudio. 

Could you try and contribute? > flywire

**Comment by flywire** [comment]
I agree the idea of programmer writing noob instructions is dumb. Assign it to me and I'll seek your guidance as required.

**Comment by Dijji** [comment]
Simple instructions added. Thanks halueda!
