### ISSUE TITLE
Display Version

### ISSUE THREAD

**Issue by flywire** [Dijji/XstReader#18]
Version should be displayed in user interface

**Comment by flywire** [comment]
Trying to add an _i_ button but I can't display a form and all the toolbox controls are dimmed out :frowning_face:

**Comment by Dijji** [comment]
You are right, if the version is to be displayed, it should be on a pop-up window launched by a button on the main screen. However, I can't say I see displaying a version as a particularly important requirement. Why do you think it is needed?

Going down the route of adding it for yourself is a good idea, even if it is tricky at first. And if you succeed, feel free to contribute your source back to the project for incorporation, ideally using a pull request.

Dijji

**Comment by flywire** [comment]
Version displayed on Properties, Details, Product Version

**Comment by flywire** [comment]
Version number is a bit hard to pick up.
```
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            string msg = "View Microsoft Outlook Mail files" + Environment.NewLine;
            msg = msg + Environment.NewLine;
            string Repository = "https://github.com/Dijji/XstReader";
            msg = msg + "Repository: " + Repository + Environment.NewLine;
            msg = msg + "Version: ";
            //Version version = new Version(Application.ProductVersion);
            //MessageBox.Show(msg + version.ToString(), "About XstReader");
            MessageBox.Show(msg, "About XstReader");
                        
        }
```

**Comment by Dijji** [comment]
What button is triggering this? I've tried very hard to avoid screen clutter.

This works, but if I were doing this, I would probably do it as a pop-up panel, to give me proper control over layout, and maybe allow for extensions in the information shown, or adding settings (maybe, for instance, to display print headers)
