### ISSUE TITLE
Is there any way to save an email or a ItemAttachment to eml file?

### ISSUE THREAD

**Issue by vphoenix** [Dijji/XstReader#21]
Hello.
I'm looking for the way to handle pst file, XstReader is excellent.
I want to save an email or a ItemAttachment (an attachment which IsEmail is true) to eml file, but I can't find the way.
Is there any method to get whole email's MimeContent?

**Comment by Dijji** [comment]
If you right click on an email in a folder, you can choose Export Email. This will save the body of the email in one of three formats: HTML, RTF or text, depending on the format of the email itself. In all three cases, a mail header is injected above the actual email body. In the case of a pure text email, the result is very close to an .eml file as most implementations interpret it. In the other two cases, you can get to .eml format (which as far as I know, only says anything about pure text files) by converting them to text using open tools, such as a browser or OpenOffice, but of course, this is a very lossy process.

Dijji

**Comment by vphoenix** [comment]
thanks a lot!
