### ISSUE TITLE
Powershell Export Issue

### ISSUE THREAD

**Issue by ryonm** [Dijji/XstReader#4]
Using Outlook 2010 & Exchange 2010.  When I create a PST using Outlook I don't have any issues.  When I export a mailbox to a PST using the PowerShell command below from the Exchange server I am no longer able to see/expand sub folders.

New-MailboxExportRequest -Mailbox jdoe@consoto.com -FilePath \\server\d$\jdoe\backup_2018_03_15.pst

Thank you.

**Comment by Dijji** [comment]
Unfortunately, I do not have any access to a copy of Exchange Server, which as far as I can tell is necessary to reproduce this issue.

If you could provide me with a sample exported PST file, then I will take a look. Obviously, I’m not interested in looking at anybody’s emails, so it might make sense to create a test account with fairly minimal contents for this purpose.

Dijji

**Comment by ryonm** [comment]
Thanks for looking into this issue.  Please download a test pst file and a screenshot of the folder structure from:

https://files.southlandcu.org/app?operation=pubopp&id=1535469318215X10A3A70A40jMpAc

**Comment by Dijji** [comment]
I've got the files and can reproduce the problem. I'll take a look.

Thanks.

Dijji

**Comment by Dijji** [comment]
Fixed in Version 1.3

**Comment by ryonm** [comment]
Confirmed, I'm now able to see sub-folders.

I am observing another issue where I'm not able to see the details of some items, I have another sample file and screenshot:

https://files.southlandcu.org/app?operation=pubopp&id=1535578208715X10A3A70A40RaDLX

Thank you.

**Comment by Dijji** [comment]
I’m glad that folder hierarchies are now working as you would expect.

As for the second problem, the.listen item highlighted in your screenshot is a Contact, and, unlike Outlook, I don’t have a content visualisation for contacts, only for emails.

There are two reasons why: firstly, my main focus was emails; and secondly, there is another mechanism already available to see the data.  If you use the radio buttons at the bottom right to switch to the Properties view, you will see all of the properties, including the ones you would expect Outlook to show.

Dijji

**Comment by ryonm** [comment]
Without paying too much attention, I was under the impression that one of my contacts was displaying properly using the 'Content' view.  This particular contact has information in the "Notes" field, and that information did show with the 'Content' view.  But yes, using the 'Properties' view shows the desired information.

Thanks again for the quick fix and this very useful tool.
