### ISSUE TITLE
Extract permanently deleted items

### ISSUE THREAD

**Issue by thims** [Dijji/XstReader#45]
Hi! Is is possible to add a switch to xstexport to extract permanently deleted items (before PST is compacted, of course)?

**Comment by Dijji** [comment]
That's an intriguing question. Fortunately, the published documentation specifies the actions taken when, say, a message is deleted. What happens is that the node containing the table defining the message is removed from the node database, meaning that there is no way to find its starting point in the file. The situation is quite exactly analogous to reading a permanently deleted NTFS file: the only way to recover it is to scan the whole disk/file for unused areas, and try to interpret them. The PST case is made worse by the fact that a message is often made up of scattered nodes containing addressees, attachments, message body, et cetera which will also have been deleted by removal from the node database, if there are no other references to them, and so will also have to be found and put together, whereas a file may typically consist of only one or a few streams.

So, not impossible, but not easy at all, and not something that I would undertake myself.

**Comment by thims** [comment]
Makes sense. Thank you!
