### ISSUE TITLE
Timestamp in UTC

### ISSUE THREAD

**Issue by vikas891** [Dijji/XstReader#52]
I asked around but to no avail. Is the date/time recorded in an OST/PST in UTC? 

I ran a few tests and XstReader correctly displays the LOCAL TIME on the source machine when the email was sent/received. The time-zone of the host where you are executing XstReader  does not matter, which is a good thing. 

Any idea the times could be parsed in UTC as that's the forensic gold standard?

Thanks,
Vikas

**Comment by iluvadev** [comment]
I don't know if all DateTime properties in an OST/PST file are in UTC, but the information about message delivery, submitted and last modification are in UTC, according to the MS specification [[MS-OXPROPS]](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148)

The properties used in XstReader for DateTime information in messages are:
- Message Submitted: [PidTagClientSubmitTime](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/ca98145f-7f87-42b4-b0ef-124c6c6f8d83)
- Message Delivered: [PidTagMessageDeliveryTime](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/76c027d8-c871-4e40-9a14-28f6596a7732)
- Message/Attachment LastModification: [PidTagLastModificationTime](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/16f0a603-8545-4da0-a3e9-0fa197e86200)

In the linked docs, MS says that all these DateTime info are in UTC.

Is this what you need?

**Comment by vikas891** [comment]
That's it! @iluvadev 👍 
I couldn't find your Twitter handle to thank you. 
https://twitter.com/vikas891/status/1478252358819725312
