### ISSUE TITLE
JSON export

### ISSUE THREAD

**Issue by halueda** [Dijji/XstReader#9]
An proposal of enhancement: Export JSON file Instead of CSV.
JSON is rather modern format than CSV, that it cares multilingual character and multiple lines.
Almost all programming language library can read/write JSON file and jq command is one of portable tool to select column, filter records and so on.

**Comment by Dijji** [comment]
Do you have any requirement for this?

In general, I have avoided exporting formats that require additional programming to consume. My experience so far is that that the majority of my consumers do not have programming skills. The main counterexample for this project to date simply tore off the UI and consumed the C# objects directly!

Dijji

**Comment by halueda** [comment]
I agree that many user does not have programming skill.

As you know some encoding include bytes of " and , in a part of a character and excel and other CVS tools fails to separate columns in such case.
I thought rather new file format like JSON is ready for such treatment.

But, I found CVS is enough if text is encoded carefully, like with utf-8.

I still think JSON is a good idea when to export all the message, message body, property and attachments.
But I agree it is very limited use case.

--HAL
